name: expense 
networks:
  default:
    name: expense
services:
  mysql:
    container_name: mysql 
    image: mysql:v1.0
  backend:
    container_name: backend
    image: backend:v1.0 
    depends_on:
      - mysql
  frontend:
    container_name: frontend
    image: frontend:v1.0 
    depends_on:
      - backend
    ports:
      - 80:80
